[build]
  publish = "openredsoftware/public"
  command = "cd openredsoftware && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
